//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use crate::library::deserialization::{de_opt_i32};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(
    schema_name = "feeder_master",
    table_name = "evaluasi_kelas"
)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub id_registrasi_mahasiswa: Option<Uuid>,
    pub id_mahasiswa: Option<Uuid>,
    pub id_semester: Option<String>,
    pub nama_semester: Option<String>,
    pub nim: Option<String>,
    pub nama_mahasiswa: Option<String>,
    pub angkatan: Option<String>,
    pub id_prodi: Option<Uuid>,
    pub nama_program_studi: Option<String>,
    pub id_status_mahasiswa: Option<String>,
    pub nama_status_mahasiswa: Option<String>,
    pub ips: Option<f32>,
    pub ipk: Option<f32>,
    pub sks_semester: Option<f32>,
    pub sks_total: Option<f32>,
    pub biaya_kuliah_smt: Option<f32>,
    pub status_sync: Option<String>,
    pub sync_at: Option<DateTime>,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub created_at: Option<DateTime>,
    pub updated_at: Option<DateTime>,
    pub deleted_at: Option<DateTime>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FeederDataModel {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id_komponen_evaluasi: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub id_kelas_kuliah: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", deserialize_with = "de_opt_i32")]
    pub id_jenis_evaluasi: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub nama: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub nama_inggris: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", deserialize_with = "de_opt_i32")]
    pub nomor_urut: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none", deserialize_with = "de_opt_i32")]
    pub bobot_evaluasi: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub tgl_create: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
